name: Pytest

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libglu1
        python -m pip install --upgrade pip
        pip install .
        pip install pytest
    - name: Test with pytest
      run: |
        pytest tests